### ISSUE TITLE
More samples in documentation

### ISSUE THREAD

**Issue by gregpettit** [vmasto/grunt-autonav#1]
The example shows how to process an individual file and output it to an individual file elsewhere.

What I would love to see (if the plugin can do this) is a sample for "process an entire directory full of HTML files and spit it back out with autonavs".

Sample of what I tried (didn't really expect it to work, but tried anyhow):

```
autonav: {
      options: {
        parent: '.nav'
      },
      dev: {
        src: '<%= dirs.purgatory %>/html/**/*.html',
        dest: '<%= dirs.dev %>'
      }
    }
```

This is meant to navigate into my "purgatory" HTML folder, grab the HTML files within, and then spit them back out into my "dev" folder.

This is the error I get:

"Warning: Unable to read "purgatory/html/download.html,purgatory/html/upload.html" file (error code: ENOENT). Use --force to continue."

Somehow the engine is able to spot that I have two files in there (download.html and upload.html) but the plugin doesn't want to accept that source, it seems.

**Comment by vmasto** [comment]
I'd try to wrap the src folder in an array. 

`src: [<%= dirs.purgatory %>+'/html/**/*.html'],`

**Comment by gregpettit** [comment]
I had tried that as my first attempt actually, but I wanted to try again to be sure. Unfortunately, it doesn't work wrapped as an array either. Exact same error. The fact that it lists the files in question shows that the Grunt globber is able to find all of the files that need to be processed, but the hand-off to autonav just doesn't work. My guess is that autonav isn't expecting an array as input, it is expecting a single string indicating just one file. It treats the array as a single string and it then just breaks.

Or, my syntax is still just wrong somehow. ;) It could still be user error!

**Comment by gregpettit** [comment]
To support the theory, I did a single file task:

```
autonav: {
      options: {
        parent: '.nav'
      },
      dev: {
        src: '<%= dirs.purgatory %>/html/upload.html',
        dest: '<%= dirs.dev %>/upload.html'
      }
    }
```

And it works as expected. But nobody will want to do one file at a time! The ability to pass in an array from Grunt's globbing syntax is a must-have for scaling the application.

Note, this one also did not work:

```
autonav: {
      options: {
        parent: '.nav'
      },
      dev: {
        src: '<%= dirs.purgatory %>/html/upload.html',
        dest: '<%= dirs.dev %>'
      }
    }
```

In which I would have expected the filename to be taken from the source. Instead, it tries to write a file called "dev" (my dirs.dev name).

**Comment by gregpettit** [comment]
Sooo.... I'm a step closer here thanks to someone on StackOverflow. They suggested that for dynamic file lists, I need to use the `expand` option. The new configuration is:

```
    autonav: {
      options: {
        parent: '.nav'
      },
      dev: {
          expand: true,
          src: '<%= dirs.purgatory %>/html/**/*.html',
          dest: '<%= dirs.dev %>'
      }
    },
```

It finally processes all 4 files! However, it doesn't make the copy to the destination. They are still sitting in purgatory. So that's my next area of debugging I need to undertake. :) The copy to destination happens when I process only one file like this:

```
    autonav: {
      options: {
        parent: '.nav'
      },
      dev: {
          src: '<%= dirs.purgatory %>/html/download.html',
          dest: '<%= dirs.dev %>/download.html'
      }
    }
```

The above is the only pattern I've been able to use to successfully process a single file. Multiple files have my stymied still!

**Comment by gregpettit** [comment]
I got it to work! Here is the final working task:

```
autonav: {
      options: {
        parent: '.nav'
      },
      dev: {
        files: [{
            expand: true,
            cwd: '<%= dirs.purgatory %>/html',
            src: '**/*.html',
            dest: '<%= dirs.dev %>'
          }
        ]
      }
    }
```

If you don't expand true and issue a cwd, it tries to recreate the whole path in the destination. I had a purgatory directory in there that had escaped my notice, but when I saw it, that was my clue. Reminded me of a past task I had the same user error on (my error I mean) and I remembered what the solution was.

Hooray!

**Comment by vmasto** [comment]
Oh nice, glad you worked it out :dancer: 

Not sure why this works for me without expanding though.

**Comment by gregpettit** [comment]
Not sure! I thought expand had to be true to even access the CWD command...? Odd!
